# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-28 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0002_auto_20170728_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('thumbnail', models.URLField()),
                ('rate', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
