# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-01 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0003_tvs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='movies',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tvs',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
