# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-07 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0005_auto_20170807_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gameID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='movieID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tv',
            name='tvId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
