# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0002_auto_20170823_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='accessImg',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='accessImg',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tv',
            name='accessImg',
            field=models.CharField(max_length=50),
        ),
    ]
