# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0003_auto_20170823_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='summary',
        ),
        migrations.AddField(
            model_name='movie',
            name='movieCode',
            field=models.IntegerField(default=20158485),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='scoreAct',
            field=models.IntegerField(default=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='scoreDirector',
            field=models.IntegerField(default=99),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='scoreFresh',
            field=models.IntegerField(default=88),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='scoreOST',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='scoreStory',
            field=models.IntegerField(default=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='scoreVisual',
            field=models.IntegerField(default=70),
            preserve_default=False,
        ),
    ]
