# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detail', '0003_auto_20170823_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviewGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('comment', models.CharField(max_length=2000)),
                ('score', models.FloatField()),
                ('contentsId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detail.Game')),
            ],
        ),
        migrations.CreateModel(
            name='reviewMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('comment', models.CharField(max_length=2000)),
                ('score', models.FloatField()),
                ('contentsId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detail.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='reviewTV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('comment', models.CharField(max_length=2000)),
                ('score', models.FloatField()),
                ('contentsId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detail.TV')),
            ],
        ),
    ]
