# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmovie',
            name='nonRecommend',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewmovie',
            name='recommend',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
